services:
  postgres_dev:
    image: reelfake/db_dev
    env_file: dev.env
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: db-dev
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'max_wal_size=4GB']
    profiles:
      - dev

  postgres_test:
    image: reelfake/db_test
    env_file: test.env
    build:
      context: .
      dockerfile: ./Dockerfile-test
    container_name: db-test
    ports:
      - '5433:5432'
    command: ['postgres', '-c', 'max_wal_size=4GB']
    profiles:
      - test
