services:
  postgres_dev:
    image: reelfake/db_dev
    env_file: dev.env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: db-dev
    ports:
      - '5432:5432'
    command:
      [
        'postgres',
        '-c',
        'max_wal_size=4GB',
        '-c',
        'shared_preload_libraries=pg_cron',
        '-c',
        'cron.database_name=reelfake_db_dev',
      ]
    profiles:
      - dev

  postgres_test:
    image: reelfake/db_test
    env_file: test.env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile-test
    container_name: db-test
    ports:
      - '5433:5432'
    command:
      [
        'postgres',
        '-c',
        'max_wal_size=4GB',
        '-c',
        'shared_preload_libraries=pg_cron',
        '-c',
        'cron.database_name=reelfake_db_test',
      ]
    profiles:
      - test
